fileserver/dashboard/urls.py
from django.urls import path
from .views import dashboard, upload_file, update_file,delete_file, confirm_delete_file
urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('/upload', upload_file, name='upload_file'),
    path(r'^update/(?P<pk>/d+)$', update_file, name='update_file'),
    path(r'^delete/(?P<pk>/d+)$', delete_file, name='delete_file'),
    path(r'^confirm-delete/(?P<pk>/d+)$', confirm_delete_file, name='confirm_delete_file'),
]

fileserver/fileserver/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import RedirectView

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('accounts', include('accounts.urls')),
                  path('library', include('library.urls')),
                  path('dashboard', include('dashboard.urls')),
                  path('', RedirectView.as_view(url='/library'))
              ]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

handler404 = 'library.views.error_404_view'

fileserver/library/urls.py
from django.urls import path
from .views import home_page, file_preview, sort_files, download_file, send_email_with_attachment, send_mail
urlpatterns = [
    path('', home_page, name='index'),
    path(r'^preview/(?P<pk>/d+)$', file_preview, name='preview'),
    path('/sort-files/<str:sortby>/', sort_files, name='sort_files'),
    path(r'^download/(?P<pk>/d+)$', download_file, name='download'),
    path(r'^email/(?P<pk>/d+)$', send_email_with_attachment, name='email'),
    path('/send-mail', send_mail, name='send-mail'),
]

fileserver/dashboard/models.py
from django.db import models

# Create your models here.

fileserver/library/models.py
from django.db import models
from django.shortcuts import reverse
import os
from django.conf import settings


def upload_to(instance, filename):
    if instance.file_type == 'audio':
        return os.path.join('media/', filename)
    else:
        pass


class Files(models.Model):
    title = models.CharField(max_length=255, help_text='title', blank=False)
    description = models.CharField(max_length=255, help_text='description', blank=True)
    file_url = models.CharField(max_length=255, help_text='url', blank=True)
    file = models.FileField(help_text='file', blank=True, upload_to='files/')
    file_type = models.CharField(max_length=2550000000, help_text='', blank=True)
    published = models.DateTimeField(auto_now_add=True, blank=True)

    def __str__(self):
        return self.title

    def get_file_type(self):
        return str(self.file_type.split('/')[-1])

    def get_absolute_url(self):
        return reverse('preview', args=[str(self.id)])

    def get_download_url(self):
        return reverse('download', args=[str(self.id)])

    def get_email_url(self):
        return reverse('email', args=[str(self.id)])

    def select_file_url(self):
        return reverse('email', args=[str(self.id)])

    def get_update_url(self):
        return reverse('update_file', args=[str(self.id)])

    def get_delete_url(self):
        return reverse('delete_file', args=[str(self.id)])

    def get_confirm_delete_url(self):
        return reverse('confirm_delete_file', args=[str(self.id)])


class FileTracker(models.Model):
    file = models.OneToOneField(Files, on_delete=models.CASCADE)
    downloads = models.IntegerField(default=0)
    emails = models.IntegerField(default=0)

    def __str__(self):
        return self.file.title

# 530
# 151

fileserver/dashboard/forms.py
from django import forms

class SearchForm(forms.Form):
    query = forms.CharField(label='Search', max_length=100)

fileserver/dashboard/views.py
import os

from django.contrib.auth.decorators import permission_required
from django.core.paginator import Paginator
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.db.models import Q

from library.formss import FileForm
from library.models import FileTracker
from library.models import Files
from accounts.models import User

from dashboard.firebase_upload import uploadfile, delete_firebase_file




@permission_required('user.can_add_files', raise_exception=True)
def dashboard(request):
    if request.method == 'POST':
        query = request.POST.get('q')
        if query:
            files = FileTracker.objects.filter(Q(file__title__icontains=query) | Q(file__description__icontains=query))
        else:
            files = FileTracker.objects.all()

    if request.method == 'GET':
        query = ''
        files = FileTracker.objects.all()

    paginator = Paginator(files, 3)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    file_count = FileTracker.objects.count()
    users_count = User.objects.count()
    users = User.objects.all()
    categories = [
        'Pdf',
        'Audio',
        'Video',
        'Images'
    ]

    data = {'categories': categories, 'count': file_count, 'users_count': users_count}
    return render(request, 'dashboard.html', {'page_obj': page_obj, 'users': users, 'data': data, 'query': query})


@permission_required('user.can_add_files', raise_exception=True)
def upload_file(request):
    if request.method == 'GET':
        form = FileForm()
        return render(request, 'add-file.html', {'form': form})
    if request.method == 'POST':
        form = FileForm(request.POST)

        if form.is_valid():
            file_obj = form.save(commit=False)
            file_obj.file_url = uploadfile(request.FILES['file'])
            file_tracker = FileTracker()
            file_tracker.file = file_obj
            file_obj.save()
            file_tracker.save()
            return redirect(reverse('dashboard'))
            return render(request, 'add-file.html', {'form': form})
        else:
            return render(request, 'add-file.html', {'form': form})


@permission_required('user.can_add_files', raise_exception=True)
def update_file(request, pk):
    file = get_object_or_404(Files, pk=pk)
    if request.method == 'GET':
        form = FileForm(instance=file)
        return render(request, 'update-file.html', {'form': form})

    if request.method == 'POST':
        form = FileForm(request.POST, request.FILES, instance=file)
        if form.is_valid():
            form.save()
            return redirect(reverse('dashboard'))
        else:
            return render(request, 'update-file.html', {'form': form})


@permission_required('user_can_delete_file', raise_exception=True)
def delete_file(request, pk):
    file = get_object_or_404(Files, pk=pk)
    return render(request, 'delete-file.html', {'file': file})


@permission_required('user_can_delete_file', raise_exception=True)
def confirm_delete_file(request, pk):
    file = get_object_or_404(Files, pk=pk)
    name = file.file_url.split('/')[-1].replace('%20', ' ')
    delete_firebase_file(name)
    file.delete()
    return redirect(reverse('dashboard'))

fileserver/dashboard/templates/add-file.html
{% extends 'base.html' %}
{% block title %} Add File {% endblock %}
{% block content %}
<div class="h-screen  login bg-cover">
    <div class="container mx-auto h-full flex flex-1 justify-center items-center">
        <div class="w-full max-w-lg">
            <div class="leading-loose" style="text-align:start">
                <form class="max-w-sm m-4 p-10 " method="POST" enctype="multipart/form-data" id="form">
                    {% csrf_token %}

                    {{form.as_p}}

                    <p style="margin-top:auto">

                        <button type="submit" class="open-btn bg-primary text-blue-500">
                            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor"
                                 class="bi bi-upload" viewBox="0 0 16 16">
                                <path d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5z"/>
                                <path d="M7.646 1.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1-.708.708L8.5 2.707V11.5a.5.5 0 0 1-1 0V2.707L5.354 4.854a.5.5 0 1 1-.708-.708l3-3z"/>
                            </svg>
                        </button>
                    </p>
                </form>

            </div>
        </div>
    </div>
</div>
{% include 'modal.html' %}
<style>


    form{
    display:flex; justify-content:center; flex-direction:row; gap:10px; flex-wrap:no-wrap;

    }

    #id_title, #id_description, #id_file{
    border:1px solid blue;
    border-radius:10px;
    height:100px;
    width:300px
    }

 #id_file{
    border:1px solid blue;
    border-radius:10px;
    height:100px;
    width:200px
    }

    button{
    display:flex; flex-direction-column;
    text-align:center;
    margin-top:-30px;
        border:1px solid blue;
    border-radius:10px;
    height:100px;
    width:100px
    }

    button svg{
    margin:auto;

    }




    form p:nth-child(5){
     display:none
    }

    form p:nth-child(6){
     display:none
    }

    .helptext{
    display:none;
   }

</style>


<script>
const fileType = document.getElementById('id_file_type')
const fileInput = document.getElementById('id_file')


fileInput.addEventListener('change', (e) => {
    const filetype = e.target.files[0]['type']
    fileType.value = filetype
})

</script>



{% endblock %}

fileserver/dashboard/templates/dashboard.html
{% extends 'base.html' %}

{% block content %}


<div class="w-full h-screen bg-white shadow-xl rounded-lg flex overflow-x-auto custom-scrollbar">
    <div class="w-64 px-4">
        <div class="h-16 flex items-center">
            <a href="{% url 'upload_file' %}" class="w-48 mx-auto bg-blue-600 hover:bg-blue-700 flex items-center justify-center text-gray-100 py-2 rounded space-x-2 transition duration-150">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"></path>
                </svg>
                <span>Upload File</span>
            </a>
        </div>
       {% with data=data %}
        {% include 'sidebar.html' with data=data %}
        {% endwith %}
    </div>
    <div class="flex-1 px-2" x-data="{ checkAll: false, filterMessages: false }">
        <div class="h-16 flex items-center justify-between">
            <div class="flex items-center">
                <div class="relative flex items-center px-0.5 space-x-0.5">
                    <div x-show="filterMessages" @click.away="filterMessages = false" class="bg-gray-200 shadow-2xl absolute left-0 top-6 w-32 py-2 text-gray-900 rounded z-10" style="display: none;">

                    </div>
                </div>
                <div class="flex items-center">
                    <div class="flex items-center ml-3">
                        <a href="{% url 'dashboard' %}" title="Reload" class="text-gray-700 px-2 py-1 border border-gray-300 rounded-lg shadow hover:bg-gray-200 transition duration-100">
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15"></path>
                            </svg>
                        </a>
                    </div>
                    <span class="bg-gray-300 h-6 w-[.5px] mx-3"></span>
                    <div class="flex items-center space-x-2">
                          {% with data=query %}
                            {% include 'searchbar.html' with data=data %}
                        {% endwith %}
                    </div>
                    <span class="bg-gray-300 h-6 w-[.5px] mx-3"></span>
                    <div class="flex items-center space-x-2">

                    </div>
                </div>
            </div>
            <div class="px-2 flex items-center space-x-4">
                <span class="text-sm text-gray-500">{{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</span>
                <div class="flex items-center space-x-2">
                     {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">
                  <button class="bg-gray-200 text-gray-400 p-1.5 rounded-lg" title="Newer">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                            <path fill-rule="evenodd" d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z" clip-rule="evenodd"></path>
                        </svg>
                    </button>
            </a>
        {% endif %}

                     {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}"> <button class="bg-gray-200 hover:bg-gray-300 text-gray-700 p-1.5 rounded-lg transition duration-150" title="Older">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                            <path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd"></path>
                        </svg>
                    </button></a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}


                </div>
            </div>
        </div>
        <div class="bg-white-100 mb-6">
            <ul class="" id="files">

               {% if page_obj %}
                {% for file in page_obj%}
                {% with data=file %}
                 {% include 'file-item.html' with data=file %}
                 {% endwith %}
                {% endfor %}
                {% else%}
                {% endif %}

            </ul>

                 <ul class="hidden" id="users">

               {% if users %}
                {% for user in users%}
                {% with data=user %}
                 {% include 'users.html' with data=user %}
                 {% endwith %}
                {% endfor %}
                {% else%}
                {% endif %}

            </ul>
        </div>
    </div>
</div> <script src="https://unpkg.com/flowbite@1.3.4/dist/flowbite.js"></script>
<script>
    const filesCon = document.getElementById('files')
    const usersCon = document.getElementById('users')

     const filesBtn = document.getElementById('files-f')
    const usersBtn = document.getElementById('users-f')

    usersBtn.addEventListener('click', ()=>{
         filesCon.classList.add('hidden')
         usersCon.classList.remove('hidden')

         usersBtn.classList.add('bg-gray-200')
         filesBtn.classList.remove('bg-gray-200')
    })

     filesBtn.addEventListener('click', ()=>{
         filesCon.classList.remove('hidden')
         usersCon.classList.add('hidden')

          usersBtn.classList.remove('bg-gray-200')
         filesBtn.classList.add('bg-gray-200')
    })
</script>
{% endblock %}

fileserver/dashboard/templates/delete-file.html
{%extends 'base.html' %}
{% block content %}

<style>
    :root { font-family: 'Inter', sans-serif; }
@supports (font-variation-settings: normal) {
  :root { font-family: 'Inter var', sans-serif; }
}
</style>
<div class="h-screen login bg-cover bg-white">
<div class="container mx-auto h-full bg-white flex flex-1 justify-center items-center">
    <div class="w-full max-w-lg">

<div class="py-10   antialiased font-medium text-gray-800 bg-white " x-data="{ modal: true }">
    <div class="max-w-sm p-2 mx-auto bg-white border-[1px] bg-white shadow rounded-xl hover:shadow-lg transition-all duration-150 ease-linear" x-show="modal"
    x-transition:enter="transition ease-out duration-300"
        x-transition:enter-start="opacity-0 scale-90"
        x-transition:enter-end="opacity-100 scale-100"
        x-transition:leave="transition ease-in duration-300"
        x-transition:leave-start="opacity-100 scale-100"
        x-transition:leave-end="opacity-0 scale-90"
    >
            <div class="relative p-6">

                <h1 class="text-3xl font-bold">{{file.title}}</h1>
                <p class="text-sm text-gray-500">Are you sure you want to delete this?</p>
                <div class="flex flex-row mt-6 space-x-2 justify-evenly">
                    <a href="{{ file.get_confirm_delete_url }}" class="w-full py-3 text-sm font-medium text-center text-white transition duration-150 ease-linear bg-red-600 border border-red-600 rounded-lg hover:bg-red-500">Delete</a href="">
                    <a href="{% url 'dashboard' %}" x-on:click="modal = ! modal" class="w-full py-3 text-sm text-center text-gray-500 transition duration-150 ease-linear bg-white border border-gray-200 rounded-lg hover:bg-gray-100">Cancel</a>
                </div>
            </div>
    </div>
</div>
      </div>

</div>
</div>
{% endblock %}

fileserver/dashboard/templates/file-item.html
{% load filters %}

<li class="flex items-center border-y hover:bg-gray-200 px-2">

    <div x-data="{ messageHover: false }" @mouseover="messageHover = true" @mouseleave="messageHover = false"
         class="w-full flex items-center justify-between p-1 my-1 cursor-pointer">
        <div class="flex items-center">
            <div class="flex items-center mr-4 ml-1 space-x-1">
                <a href="{{ data.file.get_delete_url }}" title="Not starred">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                         class="bi bi-trash3 hover:fill-blue-500 h-5 w-5" viewBox="0 0 16 16">
                        <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5ZM11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H2.506a.58.58 0 0 0-.01 0H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1h-.995a.59.59 0 0 0-.01 0H11Zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5h9.916Zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47ZM8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5Z"/>
                    </svg>
                </a>
                <a href="{{ data.file.get_update_url }}" title="Click to mark this email as important">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                         class="bi bi-pencil-square  hover:fill-blue-500 h-5 w-5" viewBox="0 0 16 16">
                        <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                        <path fill-rule="evenodd"
                              d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                    </svg>
                </a>
                <a href="{{ data.file.get_absolute_url }}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye hover:fill-blue-500 h-5 w-5"
                         viewBox="0 0 16 16">
                        <path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8zM1.173 8a13.133 13.133 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5c2.12 0 3.879 1.168 5.168 2.457A13.133 13.133 0 0 1 14.828 8c-.058.087-.122.183-.195.288-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5c-2.12 0-3.879-1.168-5.168-2.457A13.134 13.134 0 0 1 1.172 8z"/>
                        <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5zM4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0z"/>
                    </svg>
                </a>
            </div>
            <span class="w-56 pr-2 truncate">{{data.file.title}} - <span class="text-gray-500">{{data.file.get_file_type|extensions}}</span></span>

            <span class="mx-1">-</span>
            <span class="w-96 text-gray-600 text-sm truncate">{{data.file.description}}</span>
        </div>
        <div class="w-70 flex items-center justify-end">


            <div x-show="messageHover" class="flex items-center space-x-2 mx-3 gx-5" style="display: flex;">
                <button title="Downloads">

                    <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor"
                         class="bi bi-download  hover:text-gray-900 h-5 w-5" viewBox="0 0 16 16">
                        <path d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5z"/>
                        <path d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3z"/>
                    </svg>
                    {{file.downloads}}
                </button>

                <button title="Emailed" class="px-4">

                    <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor"
                         class="bi bi-envelope hover:text-gray-900 h-5 w-5" viewBox="0 0 16 16">
                        <path d="M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V4Zm2-1a1 1 0 0 0-1 1v.217l7 4.2 7-4.2V4a1 1 0 0 0-1-1H2Zm13 2.383-4.708 2.825L15 11.105V5.383Zm-.034 6.876-5.64-3.471L8 9.583l-1.326-.795-5.64 3.47A1 1 0 0 0 2 13h12a1 1 0 0 0 .966-.741ZM1 11.105l4.708-2.897L1 5.383v5.722Z"/>
                    </svg>
                    {{data.emails}}
                </button>

            </div>

        </div>
    </div>
</li>

fileserver/dashboard/templates/update-file.html
{% extends 'base.html' %}
{% block title %} Update File {% endblock %}
{% block content %}


<div class="h-screen  login bg-cover">
    <div class="container mx-auto h-full flex flex-1 justify-center items-center">

        <div class="w-full max-w-lg">
            <div class="leading-loose" style="text-align:start">

                <form class="max-w-sm m-4 p-10 " method="POST" enctype="multipart/form-data">
                    {% csrf_token %}

                    {{form.as_p}}

                    <p style="margin-top:auto">

                        <button type="submit" class=" open-btn bg-primary text-blue-500">
                            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor"
                                 class="bi bi-upload" viewBox="0 0 16 16">
                                <path d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5z"/>
                                <path d="M7.646 1.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1-.708.708L8.5 2.707V11.5a.5.5 0 0 1-1 0V2.707L5.354 4.854a.5.5 0 1 1-.708-.708l3-3z"/>
                            </svg>
                        </button>
                    </p>
                </form>

            </div>
        </div>
    </div>
</div>

{% include 'modal.html' %}

<style>


    form{
    display:flex; justify-content:center; flex-direction:row; gap:10px; flex-wrap:no-wrap;

    }

    #id_title, #id_description, #id_file{
    border:1px solid blue;
    border-radius:10px;
    height:100px;
    width:300px
    }

 #id_file{
    border:1px solid blue;
    border-radius:10px;
    height:100px;
    width:200px;
    }

 a{

}
    button{
    display:flex; flex-direction-column;
    text-align:center;
    margin-top:-30px;
        border:1px solid blue;
    border-radius:10px;
    height:100px;
    width:100px
    }

    button svg{
    margin:auto;

    }




    form p:nth-child(5){
     display:none
    }

      form p:nth-child(6){
     display:none
    }

    .helptext{
    display:none;
   }

</style>
<script>
const fileType = document.getElementById('id_file_type')
const fileInput = document.getElementById('id_file')

fileInput.addEventListener('change', (e) => {
    const filetype = e.target.files[0]['type']
    fileType.value = filetype
})
</script>
{% endblock %}